export interface CloudflareImage {
  id: string;
  assetType?: 'image' | 'video';
  filename: string;
  displayName?: string;
  uploaded: string;
  size?: number;
  fileSizeBytes?: number | null;
  variants?: string[];
  folder?: string;
  tags?: string[];
  description?: string;
  originalUrl?: string;
  originalUrlNormalized?: string;
  sourceUrl?: string;
  sourceUrlNormalized?: string;
  namespace?: string;
  contentHash?: string;
  altTag?: string;
  exif?: Record<string, string | number>;
  aspectRatio?: string;
  dimensions?: { width: number; height: number };
  generatedBy?: string;
  comfyMetadataDetected?: boolean;
  comfyMetadataSource?: string;
  altText?: string;
  contentType?: string;
  isAnimated?: boolean;
  animatedWebp?: {
    sourceImageIds?: string[];
    sourceFilenames?: string[];
    orderMode?: string;
    fps?: number;
    loop?: boolean;
    generatedAt: string;
    repairedFromImageId?: string;
    replacedImageId?: string;
    repairMode?: 'reverse';
  };
  parentId?: string;
  linkedAssetId?: string;
  variationSort?: number;
  videoStatus?: 'pending' | 'ready' | 'error';
  videoDurationSeconds?: number;
  videoPlaybackUrl?: string;
  videoHlsUrl?: string;
  videoThumbnailUrl?: string;
  videoPreviewUrl?: string;
  hasClipEmbedding?: boolean;
  hasColorEmbedding?: boolean;
  dominantColors?: string[];
  averageColor?: string;
}
