export const GALLERY_COMMAND_HELP = [
  'Available commands:',
  '- hide folder <name>: Temporarily remove a folder from the gallery',
  '- show folder <name>: Bring a hidden folder back into the gallery',
  '- hide namespace <name>: Immediately remove a namespace from the gallery',
  '- show namespace <name>: Bring a hidden namespace back into the gallery',
  '- hide tag <name>: Temporarily remove a tag from the gallery',
  '- show tag <name>: Filter the gallery to a specific tag',
  '- clear tag: Remove the tag filter',
  '- unhide tag <name>: Bring a hidden tag back into the gallery',
  '- list hidden folders: Show currently hidden folders',
  '- list hidden tags: Show currently hidden tags',
  '- list hidden namespaces: Show currently hidden namespaces',
  '- clear hidden: Unhide every folder',
  '- clear hidden tags: Unhide every tag',
  '- clear hidden namespaces: Unhide every namespace',
  '- list folders: List all known folders',
  '- show only folders <a,b>: Hide every folder except the listed ones',
  '- show only tags <a,b>: Hide every tag except the listed ones',
  '- parents only: Only show images that have variants',
  '- show all: Show every image, including solos',
  '- show missing clip/color/embeddings: Filter to images missing one or more embeddings',
  '- show no embeddings: Filter to images missing both CLIP and color embeddings',
  '- clear embedding filter: Remove embedding filter',
  '- last uploaded: Filter to the latest upload day',
  '- show only comfy: Filter to images with detected ComfyUI workflow metadata',
  '- clear comfy filter: Remove Comfy-only filter',
  '- page next/prev or page <n>: Navigate gallery pages',
  '- help: Show this command list'
].join(' ');
