interface Env {
  LOCAL_DEV_MODE: string;
  CLIENT_SITES_PUBLISH_SECRET?: string;
  ADMIN_API_TOKEN?: string;
  ACCESS_LINK_HASH_SECRET: string;
  SESSION_SIGNING_SECRET: string;
  IMAGES_ACCOUNT_HASH: string;
  IMAGES_SIGNING_KEY?: string;
}
